import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserNav from "./components/UserNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-100 py-4 px-6 flex gap-6 mb-8 items-center">
          <a href="/" className="font-semibold">
            Home
          </a>
          <a href="/dashboard">Dashboard</a>
          <a href="/band">My Band</a>
          <a href="/profile">Profile</a>
          <a href="/admin/dashboard">Admin</a>
          <div className="flex-1" />
          <UserNav />
        </nav>
        {children}
      </body>
    </html>
  );
}
